### ISSUE TITLE
Disable writing files to SqlTracker::Config.output_path

### ISSUE THREAD

**Issue by yoomlam** [steventen/sql_tracker#9]
The `sql_tracker-*.json` files are piling up in `SqlTracker::Config.output_path`. I'd like an option to disable writing these files as I use `SqlTracker.track` in RSpec tests.

Setting `SqlTracker::Config.output_path = nil` doesn't stop writing the files.

**Comment by steventen** [comment]
Hi @yoomlam 
Sorry for the late reply. I think currently the code does not check whether it is `nil` or not, since it assumes that the user would always need this output file. 

I think we can provide some option to disable it, but firstly, I'd like to know how do you use this in your case without the output file?

**Comment by yoomlam** [comment]
Hi @steventen,

Here's an example rspec where I'm using SqlTracker:
```ruby
          query_data = SqlTracker.track do
            document_fetcher.find_or_create_documents!
          end

          # Uncomment the following to see a count of SQL queries
          # pp query_data.values.pluck(:sql, :count)
          doc_insert_queries = query_data.values.select { |o| o[:sql].start_with?("INSERT INTO \"documents\"") }
          expect(doc_insert_queries.pluck(:count).max).to eq 1
```

Note that I don't need the files -- I only need to examine the data in `query_data`.

**Comment by steventen** [comment]
Is your rspec part of Rails application testing? My current guess is that this test is part of rails test, therefore [this](https://github.com/steventen/sql_tracker/blob/master/lib/sql_tracker.rb#L6) part is probably triggered as well. So when the test stops and the rails instance exit, it triggers the code that saves the results into a file.

**Comment by yoomlam** [comment]
Yes. The rspec is used for Rails testing.

**Comment by steventen** [comment]
I think you can probably just add `SqlTracker::Config.enabled = false` in your test config file

**Comment by yoomlam** [comment]
A `sql_tracker-81539-1614177391.json` file is still created and `query_data.values` is empty.

**Comment by steventen** [comment]
Is the file empty as well or contains some data?

**Comment by yoomlam** [comment]
It contains 4.2KB of data. Are you able to reproduce?

**Comment by steventen** [comment]
Can you make sure to add the setting in `config/environments/test.rb`:
```ruby
Rails.application.configure do
  ... ...
  SqlTracker::Config.enabled = false
end
```

**Comment by yoomlam** [comment]
Progress! Files are not created, but `query_data` is empty: `{}`.

**Comment by steventen** [comment]
Yeah, I see the problem now. The `track` block is using the options from the class attribute, therefore, when you set `enabled = false`, it would disable everything.

I think when people uses the `track` block approach, it should always make the `enabled = true`, regardless of the option at class level.

I'll create a PR to fix this shortly!

**Comment by steventen** [comment]
@yoomlam I have merged a fix into master. If you could try the master, that should fix the issue.

Thanks

**Comment by yoomlam** [comment]
@steventen Works great! Thanks! Please push out a new version of the gem.

**Comment by steventen** [comment]
The new version has just released. Thanks!
